---

- name: reenable node exporter service
  command: systemctl reenable prometheus-node-exporter.service

- name: reinit node exporter
  command: initctl reload-configuration

- name: restart node exporter
  service:
    name: prometheus-node-exporter
    state: restarted

- name: Restart firewalld
  service:
    name: firewalld
    enabled: no
    state: restarted
  when: service_firewalld_status.stdout.find("running") != -1
